import { createFileRoute, Link } from "@tanstack/react-router";
import tonyPortrait from "../assets/tony-lin.webp.asset.json";
import unilifeLogo from "../assets/unilife-royal-pacific.png.asset.json";
import { SiteHeader } from "../components/SiteHeader";
import { SiteFooter } from "../components/SiteFooter";
import { CONTACT } from "../lib/contact";

export const Route = createFileRoute("/zh-tw/about")({
  head: () => ({ meta: [{ title: "關於 Tony Lin｜大溫哥華 REALTOR®" }, { name: "description", content: "認識 Tony Lin，UniLife Realty Inc. REALTOR®，提供 Greater Vancouver 與 Fraser Valley 住宅、商用不動產及土地服務。" }, { property: "og:title", content: "關於 Tony Lin REALTOR®" }, { property: "og:url", content: "/zh-tw/about" }, { property: "og:image", content: tonyPortrait.url }], links: [{ rel: "canonical", href: "/zh-tw/about" }, { rel: "alternate", hrefLang: "en-CA", href: "/about" }, { rel: "alternate", hrefLang: "zh-Hant", href: "/zh-tw/about" }] }),
  component: AboutZh,
});

function AboutZh() { return <div className="min-h-dvh"><SiteHeader locale="zh-TW" /><main><section className="luxury-wave-bg luxury-wave-rise px-6 py-20"><div className="mx-auto grid max-w-7xl gap-14 md:grid-cols-12"><div className="md:col-span-5"><div className="overflow-hidden rounded-3xl border border-border bg-card shadow-xl"><img src={tonyPortrait.url} alt="Tony Lin，UniLife Realty Inc. REALTOR®" className="aspect-[3/4] w-full object-cover" /></div><div className="mt-6 inline-flex rounded-xl border border-border bg-card px-5 py-3 shadow-sm"><img src={unilifeLogo.url} alt="UniLife Realty Inc. — Royal Pacific Realty Group" className="h-12 w-auto" /></div></div><div className="md:col-span-7"><p className="section-label"><span className="gold-divider mr-3" />關於 Tony</p><h1 className="mt-5 font-serif text-5xl leading-tight md:text-6xl">Tony Lin, REALTOR<sup>®</sup></h1><p className="mt-6 text-lg leading-relaxed text-foreground/80">Tony 是 UniLife Realty Inc. 的 REALTOR®，主要服務 Greater Vancouver 與 Fraser Valley。公開房源經驗涵蓋零售商用不動產、農業用地、住宅土地與 Vancouver West 住宅。</p><p className="mt-5 text-lg leading-relaxed text-foreground/80">Tony 重視把市場資訊、交易條件與可能風險說清楚。無論您是第一次買房、準備出售、配置投資，或還在評估方向，都能用 English 或國語自在討論。</p><div className="mt-10 grid gap-4 sm:grid-cols-2"><Tile label="經紀公司" value={CONTACT.brokerage} /><Tile label="辦公室" value={`${CONTACT.officeAddress}, ${CONTACT.officeCity}`} /><Tile label="直撥電話" value={CONTACT.phone} /><Tile label="Email" value={CONTACT.email} /><Tile label="服務語言" value="English · 國語" /><Tile label="辦公室電話" value={CONTACT.officePhone} /></div><div className="mt-10 flex gap-3"><Link to="/zh-tw/contact" className="rounded-full bg-foreground px-6 py-3 text-sm font-medium text-background">預約諮詢</Link><Link to="/zh-tw/listings" className="rounded-full border border-foreground/30 px-6 py-3 text-sm font-medium">查看房源</Link></div></div></div></section></main><SiteFooter locale="zh-TW" /></div>; }
function Tile({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-border bg-card p-5"><p className="text-[0.62rem] uppercase tracking-[0.22em] text-primary">{label}</p><p className="mt-2 font-serif text-base">{value}</p></div>; }